spring:
  application:
    name: ai-code-helper
  profiles:
    active: local
server:
  port: 8081
  servlet:
    context-path: /api
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: sk-db982a70ca96434cab197afd0b3ea495
      embedding-model:
        model-name: text-embedding-v4
        api-key: sk-db982a70ca96434cab197afd0b3ea495
      streaming-chat-model:
        model-name: qwen-max
        api-key: sk-db982a70ca96434cab197afd0b3ea495
bigmodel:
  api-key: 6805b826c4eb4147b4ca6c23bc966b0e.DDrR3aCW3qzHRFYM
